### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'plugin.promisedModules.size')

### ISSUE THREAD

**Issue by coindegen** [mehtaabGill/holt#31]
I'm getting the following error when I attempt to initialize a logger like this:

```js
export const globalPlugin = new Elysia({ name: "globalPlugin" })
  .use(html())
  .use(new HoltLogger().getLogger())
```

```sh
5610 |         );
5611 |         return this;
5612 |       }
5613 |       return instance;
5614 |     }
5615 |     if (plugin.promisedModules.size) {
               ^
TypeError: undefined is not an object (evaluating 'plugin.promisedModules.size')
      at _use (/app/node_modules/elysia/dist/index.mjs:5615:9)
            at /app/src/lib/plugin.ts:14:29
```

Versions:

```
  "dependencies": {
    "@elysiajs/html": "^1.0.2",
    "@elysiajs/server-timing": "^1.0.2",
    "@elysiajs/static": "^1.0.2",
    "@tlscipher/holt": "^1.1.3",
    "elysia": "^1.0.9",
```

**Comment by mehtaabGill** [comment]
Please try upgrading to 1.2.0 and see if the error persists.
